FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python myproject/manage.py collectstatic --noinput

EXPOSE 8000

CMD ["python", "myproject/manage.py", "runserver", "0.0.0.0:8000"]
