version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sample_bd
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python myproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=sample_bd
      - DB_USER=sample_user
      - DB_PASS=1234

volumes:
  postgres_data:
